import { ReqCreateSpace } from "@/api/space/createSpace"

export const spaceSeed: ReqCreateSpace[] = [
  {
    name: "OrchidLoft",
    location: "Sukhumvit, Bangkok",
    available: "Mon-Sat, 7AM to 9PM",
    Rooms: 20,
    Amenities: "Wifi, Fresh Coffee, Meeting Rooms, Lounge",
    Rules: "Clean up after yourself, Respect others' space",
    Community: "Designers, Entrepreneurs, Tech Professionals",
    latitude: 13.736717,
    longitude: 100.523186,
    hostId: "",
  },
  {
    name: "TigerNest",
    location: "Silom, Bangkok",
    available: "Mon-Sat, 7AM to 10PM",
    Rooms: 5,
    Amenities: "High-speed Internet, Kitchen, Projector, Chill-out-zone",
    Rules: "Guests allowed with prior notice, No outside food",
    Community: "SMEs, Remote Workers, Startups",
    latitude: 13.726238,
    longitude: 100.524125,
    hostId: "",
  },
  {
    name: "ElephantSpace",
    location: "Sathorn, Bangkok",
    available: "Mon-Fri, 7AM to 9PM",
    Rooms: 50,
    Amenities: "Mail Service, Kitchen, Meditation Room, Printer/Copier",
    Rules: "No smoking, Keep quiet in meditation room",
    Community: "Freelancers, Marketing and Media Companies",
    latitude: 13.719795,
    longitude: 100.522752,
    hostId: "",
  },
  {
    name: "CherryBlossom Point",
    location: "Chinatown, Bangkok",
    available: "Mon-Sat, 7AM to 10PM",
    Rooms: 30,
    Amenities: "Mail Service, Kitchen, Gym, Printer/Copier",
    Rules: "Keep the gym clean, No noise after 9PM",
    Community: "Tech Companies, Business Owners, Remote Teams",
    latitude: 13.739945,
    longitude: 100.508667,
    hostId: "",
  },
  {
    name: "GoldenRoof Hub",
    location: "Chatuchak, Bangkok",
    available: "Mon-Sat, 8AM to 8PM",
    Rooms: 35,
    Amenities: "En-suite Kitchen, High-speed Wifi, Meeting Room, Printer/Copier",
    Rules: "No noise pollution, Guests not allowed without notice",
    Community: "Entrepreneurs, Remote Workers, Digital Nomads",
    latitude: 13.828611,
    longitude: 100.561175,
    hostId: "",
  },
  {
    name: "JadeGarden Center",
    location: "Phra Nakhon, Bangkok",
    available: "Mon-Sat, 8AM to 10PM",
    Rooms: 40,
    Amenities: "Quiet Zones, Ergonomic Chairs, Fully Equipped Kitchen, Lounge",
    Rules: "Respect co-working space, No smoking indoors",
    Community: "Startups, Freelancers, Remote Workers",
    latitude: 13.755072,
    longitude: 100.492667,
    hostId: "",
  },
  {
    name: "RiverView Loft",
    location: "Khlong San, Bangkok",
    available: "Mon-Sat, 8AM to 9PM",
    Rooms: 60,
    Amenities: "Wifi, Pantry, Rooftop Lounge, Meeting Rooms",
    Rules: "No Noise Pollution, Keep Your Space Clean",
    Community: "Designers, Digital Nomads, Entrepreneurs",
    latitude: 13.723329,
    longitude: 100.510728,
    hostId: "",
  },
  {
    name: "Emerald Suite",
    location: "Phaya Thai, Bangkok",
    available: "Mon-Sun, 8AM to 10PM",
    Rooms: 10,
    Amenities: "Wifi, Coffee Bar, Lounge, Kitchen",
    Rules: "Keep Area Clean, No Pets Allowed",
    Community: "Remote Workers, Startup Teams, Freelancers",
    latitude: 13.785662,
    longitude: 100.543766,
    hostId: "",
  },
  {
    name: "SilkSpace",
    location: "Ratchathewi, Bangkok",
    available: "Mon-Sun, 8AM to 8PM",
    Rooms: 80,
    Amenities: "Meeting Rooms, Wifi, Printers/Copiers, Free Parking",
    Rules: "No Smoking, Respect Each Other's Space",
    Community: "Technology Companies, Digital Marketers",
    latitude: 13.751197,
    longitude: 100.528134,
    hostId: "",
  },
  {
    name: "Bamboo Park",
    location: "Pathum Wan, Bangkok",
    available: "Mon-Sat, 7AM to 9PM",
    Rooms: 50,
    Amenities: "Bike Storage, Kitchen, Wifi, Accessibility Facilities",
    Rules: "Guests Not Allowed Without Notice, Keep Your Space Clean",
    Community: "Professionals, Business Owners, Remote Teams",
    latitude: 13.734347,
    longitude: 100.553543,
    hostId: "",
  },
  {
    name: "Lotus WorkHub",
    location: "Lat Phrao, Bangkok",
    available: "Tue-Sun, 7:30AM to 9PM",
    Rooms: 25,
    Amenities: "Outdoor Terrace, Wifi, Kitchen, Lounge",
    Rules: "Respect Co-Working Space, No Outside Food",
    Community: "Freelancers, Remote Teams, Digital Nomads",
    latitude: 13.810535,
    longitude: 100.573763,
    hostId: "",
  },
  {
    name: "DoveNest Creative Space",
    location: "Bang Rak, Bangkok",
    available: "Mon-Sat, 8AM to 10PM",
    Rooms: 35,
    Amenities: "Project Spaces, Wifi, Printers/Copiers, Lounge",
    Rules: "No Pets Allowed, No Noise Pollution",
    Community: "Startups, Designers, Creative Professionals",
    latitude: 13.72052,
    longitude: 100.516326,
    hostId: "",
  },
]
